--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Valiant-Bedrock/libscoreboard
build-by-default: true
branches:
- master
projects:
  libscoreboard:
    model: virion
    type: library
...
